-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 07:45:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`event` (
  `num` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NULL,
  `all-day` VARCHAR(45) CHARACTER SET 'armscii8' BINARY NULL,
  `fromDate` DATE NOT NULL,
  `fromTime` TIME NULL,
  `fromMeridiem` VARCHAR(45) BINARY NULL,
  `toDate` DATE NOT NULL,
  `toTime` TIME NULL,
  `toMeridiem` VARCHAR(45) BINARY NULL,
  `repeat` VARCHAR(45) NULL,
  `alert` VARCHAR(45) NULL,
  `invitees` VARCHAR(45) NULL,
  `attachments` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `note` VARCHAR(45) NULL,
  `eventcol` VARCHAR(45) NULL,
  PRIMARY KEY (`num`),
  UNIQUE INDEX `num_UNIQUE` (`num` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`workers` (
  `Position` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Profession` VARCHAR(45) NOT NULL,
  `Endurance` VARCHAR(45) NOT NULL,
  `Level` INT NOT NULL,
  `Cost` INT,
  PRIMARY KEY (`Position`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE workers
DROP COLUMN Cost;

ALTER TABLE workers
ADD Cost INT;